### ISSUE TITLE
[BUG] Downgrade to numpy<2

### ISSUE THREAD

**Issue by pbarbarant** [alexisthual/fugw#62]
As raised in https://github.com/the-virtual-brain/tvb-gdist/issues/82 , `Numpy 2.0` introduces breaking changes that messes with compiled libraries. We will need to downgrade the numpy version as for now.

**Comment by rflamary** [comment]
Note that POT is now compatible with numpy 2.0+ so no need to wait for us ;)

**Comment by pbarbarant** [comment]
> Note that POT is now compatible with numpy 2.0+ so no need to wait for us ;)

POT was always cutting-edge 😉
