### ISSUE TITLE
[BUG] Mix-up between inter and intra subject weights

### ISSUE THREAD

**Issue by pbarbarant** [alexisthual/fugw#78]
In `FUGWBarycenter`, the `weights_list` arguments is passed to `update_barycenter_features`. `weights_list` describes the probability weights in each subject and not the weight of the subject in the variational formulation of the barycenter. I propose to add `subject_weights` as an argument passed to the `fit()` method in order to further avoid this confusion.

**Comment by bthirion** [comment]
I'm unsure why this parameter is important ?

**Comment by pbarbarant** [comment]
> I'm unsure why this parameter is important ?
These are the lambdas in the variational formulation:

```math
\min _\mu \sum_k \lambda_k d_{F G W, \alpha, 1, q}^{\mathbb{R}^d}\left(\mu, \mu_k\right)
```

In practice everyone gets assigned the same weight, it's essentially for the consistency with POT.

**Comment by bthirion** [comment]
But if we're sure that we never change the weights, why not hard-coding the default (to unclutter the API) ?
